// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class AppReply;
@class AppReplyBuilder;
@class AppReplyEventInfo;
@class AppReplyEventInfoBuilder;
@class AppReplyEventUUID;
@class AppReplyEventUUIDBuilder;
@class AppReplyFriendRequest;
@class AppReplyFriendRequestBuilder;
@class AppReplyUser;
@class AppReplyUserBuilder;
@class AppRequest;
@class AppRequestAcceptFriendRequest;
@class AppRequestAcceptFriendRequestBuilder;
@class AppRequestAlbumPhoto;
@class AppRequestAlbumPhotoBuilder;
@class AppRequestBuilder;
@class AppRequestCreatePrivateEvent;
@class AppRequestCreatePrivateEventBuilder;
@class AppRequestCreatePublicEvent;
@class AppRequestCreatePublicEventBuilder;
@class AppRequestEventAccept;
@class AppRequestEventAcceptBuilder;
@class AppRequestFriendRequest;
@class AppRequestFriendRequestBuilder;
@class AppRequestLoginMessage;
@class AppRequestLoginMessageBuilder;
@class AppRequestPhotoAlbum;
@class AppRequestPhotoAlbumBuilder;
@class AppRequestPollingParameters;
@class AppRequestPollingParametersBuilder;
@class AppRequestRegisterMessage;
@class AppRequestRegisterMessageBuilder;
@class AppRequestUpdateProfile;
@class AppRequestUpdateProfileBuilder;


typedef NS_ENUM(SInt32, AppRequestMessageType) {
  AppRequestMessageTypeTFriendRequest = 1,
  AppRequestMessageTypeTGetFriendRequests = 2,
  AppRequestMessageTypeTGetFriends = 3,
  AppRequestMessageTypeTAcceptFriendRequest = 4,
  AppRequestMessageTypeTCreatePublicEvent = 5,
  AppRequestMessageTypeTCreatePrivateEvent = 6,
  AppRequestMessageTypeTEventAccept = 7,
  AppRequestMessageTypeTRegistration = 9,
  AppRequestMessageTypeTLogin = 10,
  AppRequestMessageTypeTUpdateProfile = 11,
  AppRequestMessageTypeTPollNotifications = 14,
  AppRequestMessageTypeTPollNewsfeed = 13,
  AppRequestMessageTypeTPollAcceptedEvents = 12,
  AppRequestMessageTypeTUserInfoRequest = 15,
};

BOOL AppRequestMessageTypeIsValidValue(AppRequestMessageType value);
NSString *NSStringFromAppRequestMessageType(AppRequestMessageType value);

typedef NS_ENUM(SInt32, AppReplyResponseType) {
  AppReplyResponseTypeTSuccess = 1,
  AppReplyResponseTypeTMissingInput = 2,
};

BOOL AppReplyResponseTypeIsValidValue(AppReplyResponseType value);
NSString *NSStringFromAppReplyResponseType(AppReplyResponseType value);


@interface SocialRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define AppRequest_phone_id @"phoneId"
#define AppRequest_msg_type @"msgType"
#define AppRequest_reg_msg @"regMsg"
#define AppRequest_login_msg @"loginMsg"
#define AppRequest_create_private_event @"createPrivateEvent"
#define AppRequest_create_public_event @"createPublicEvent"
#define AppRequest_accept_event @"acceptEvent"
#define AppRequest_poll_params @"pollParams"
#define AppRequest_friend_request @"friendRequest"
#define AppRequest_accept_friend_request @"acceptFriendRequest"
#define AppRequest_update_profile @"updateProfile"
#define AppRequest_request_user_info @"requestUserInfo"
@interface AppRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPhoneId_:1;
  BOOL hasRegMsg_:1;
  BOOL hasLoginMsg_:1;
  BOOL hasCreatePrivateEvent_:1;
  BOOL hasCreatePublicEvent_:1;
  BOOL hasAcceptEvent_:1;
  BOOL hasPollParams_:1;
  BOOL hasFriendRequest_:1;
  BOOL hasAcceptFriendRequest_:1;
  BOOL hasUpdateProfile_:1;
  BOOL hasMsgType_:1;
  SInt64 phoneId;
  AppRequestRegisterMessage* regMsg;
  AppRequestLoginMessage* loginMsg;
  AppRequestCreatePrivateEvent* createPrivateEvent;
  AppRequestCreatePublicEvent* createPublicEvent;
  AppRequestEventAccept* acceptEvent;
  AppRequestPollingParameters* pollParams;
  AppRequestFriendRequest* friendRequest;
  AppRequestAcceptFriendRequest* acceptFriendRequest;
  AppRequestUpdateProfile* updateProfile;
  AppRequestMessageType msgType;
  PBAppendableArray * requestUserInfoArray;
}
- (BOOL) hasPhoneId;
- (BOOL) hasMsgType;
- (BOOL) hasRegMsg;
- (BOOL) hasLoginMsg;
- (BOOL) hasCreatePrivateEvent;
- (BOOL) hasCreatePublicEvent;
- (BOOL) hasAcceptEvent;
- (BOOL) hasPollParams;
- (BOOL) hasFriendRequest;
- (BOOL) hasAcceptFriendRequest;
- (BOOL) hasUpdateProfile;
@property (readonly) SInt64 phoneId;
@property (readonly) AppRequestMessageType msgType;
@property (readonly, strong) AppRequestRegisterMessage* regMsg;
@property (readonly, strong) AppRequestLoginMessage* loginMsg;
@property (readonly, strong) AppRequestCreatePrivateEvent* createPrivateEvent;
@property (readonly, strong) AppRequestCreatePublicEvent* createPublicEvent;
@property (readonly, strong) AppRequestEventAccept* acceptEvent;
@property (readonly, strong) AppRequestPollingParameters* pollParams;
@property (readonly, strong) AppRequestFriendRequest* friendRequest;
@property (readonly, strong) AppRequestAcceptFriendRequest* acceptFriendRequest;
@property (readonly, strong) AppRequestUpdateProfile* updateProfile;
@property (readonly, strong) PBArray * requestUserInfo;
- (SInt64)requestUserInfoAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppRequestBuilder*) builder;
+ (AppRequestBuilder*) builder;
+ (AppRequestBuilder*) builderWithPrototype:(AppRequest*) prototype;
- (AppRequestBuilder*) toBuilder;

+ (AppRequest*) parseFromData:(NSData*) data;
+ (AppRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequest*) parseFromInputStream:(NSInputStream*) input;
+ (AppRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define RegisterMessage_password_hash @"passwordHash"
#define RegisterMessage_nickname @"nickname"
#define RegisterMessage_is_male @"isMale"
@interface AppRequestRegisterMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIsMale_:1;
  BOOL hasPasswordHash_:1;
  BOOL hasNickname_:1;
  BOOL isMale_:1;
  NSString* passwordHash;
  NSString* nickname;
}
- (BOOL) hasPasswordHash;
- (BOOL) hasNickname;
- (BOOL) hasIsMale;
@property (readonly, strong) NSString* passwordHash;
@property (readonly, strong) NSString* nickname;
- (BOOL) isMale;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppRequestRegisterMessageBuilder*) builder;
+ (AppRequestRegisterMessageBuilder*) builder;
+ (AppRequestRegisterMessageBuilder*) builderWithPrototype:(AppRequestRegisterMessage*) prototype;
- (AppRequestRegisterMessageBuilder*) toBuilder;

+ (AppRequestRegisterMessage*) parseFromData:(NSData*) data;
+ (AppRequestRegisterMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestRegisterMessage*) parseFromInputStream:(NSInputStream*) input;
+ (AppRequestRegisterMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestRegisterMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppRequestRegisterMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppRequestRegisterMessageBuilder : PBGeneratedMessageBuilder {
@private
  AppRequestRegisterMessage* resultRegisterMessage;
}

- (AppRequestRegisterMessage*) defaultInstance;

- (AppRequestRegisterMessageBuilder*) clear;
- (AppRequestRegisterMessageBuilder*) clone;

- (AppRequestRegisterMessage*) build;
- (AppRequestRegisterMessage*) buildPartial;

- (AppRequestRegisterMessageBuilder*) mergeFrom:(AppRequestRegisterMessage*) other;
- (AppRequestRegisterMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppRequestRegisterMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPasswordHash;
- (NSString*) passwordHash;
- (AppRequestRegisterMessageBuilder*) setPasswordHash:(NSString*) value;
- (AppRequestRegisterMessageBuilder*) clearPasswordHash;

- (BOOL) hasNickname;
- (NSString*) nickname;
- (AppRequestRegisterMessageBuilder*) setNickname:(NSString*) value;
- (AppRequestRegisterMessageBuilder*) clearNickname;

- (BOOL) hasIsMale;
- (BOOL) isMale;
- (AppRequestRegisterMessageBuilder*) setIsMale:(BOOL) value;
- (AppRequestRegisterMessageBuilder*) clearIsMale;
@end

#define LoginMessage_password_hash @"passwordHash"
@interface AppRequestLoginMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPasswordHash_:1;
  NSString* passwordHash;
}
- (BOOL) hasPasswordHash;
@property (readonly, strong) NSString* passwordHash;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppRequestLoginMessageBuilder*) builder;
+ (AppRequestLoginMessageBuilder*) builder;
+ (AppRequestLoginMessageBuilder*) builderWithPrototype:(AppRequestLoginMessage*) prototype;
- (AppRequestLoginMessageBuilder*) toBuilder;

+ (AppRequestLoginMessage*) parseFromData:(NSData*) data;
+ (AppRequestLoginMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestLoginMessage*) parseFromInputStream:(NSInputStream*) input;
+ (AppRequestLoginMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestLoginMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppRequestLoginMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppRequestLoginMessageBuilder : PBGeneratedMessageBuilder {
@private
  AppRequestLoginMessage* resultLoginMessage;
}

- (AppRequestLoginMessage*) defaultInstance;

- (AppRequestLoginMessageBuilder*) clear;
- (AppRequestLoginMessageBuilder*) clone;

- (AppRequestLoginMessage*) build;
- (AppRequestLoginMessage*) buildPartial;

- (AppRequestLoginMessageBuilder*) mergeFrom:(AppRequestLoginMessage*) other;
- (AppRequestLoginMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppRequestLoginMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPasswordHash;
- (NSString*) passwordHash;
- (AppRequestLoginMessageBuilder*) setPasswordHash:(NSString*) value;
- (AppRequestLoginMessageBuilder*) clearPasswordHash;
@end

#define CreatePrivateEvent_title @"title"
#define CreatePrivateEvent_location @"location"
#define CreatePrivateEvent_start_time @"startTime"
#define CreatePrivateEvent_event_uuid1 @"eventUuid1"
#define CreatePrivateEvent_description @"pb_description"
#define CreatePrivateEvent_invited_users @"invitedUsers"
@interface AppRequestCreatePrivateEvent : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStartTime_:1;
  BOOL hasTitle_:1;
  BOOL hasLocation_:1;
  BOOL hasDescription_:1;
  BOOL hasEventUuid1_:1;
  SInt64 startTime;
  NSString* title;
  NSString* location;
  NSString* pb_description;
  NSData* eventUuid1;
  PBAppendableArray * invitedUsersArray;
}
- (BOOL) hasTitle;
- (BOOL) hasLocation;
- (BOOL) hasStartTime;
- (BOOL) hasEventUuid1;
- (BOOL) hasDescription;
@property (readonly, strong) NSString* title;
@property (readonly, strong) NSString* location;
@property (readonly) SInt64 startTime;
@property (readonly, strong) NSData* eventUuid1;
@property (readonly, strong) NSString* pb_description;
@property (readonly, strong) PBArray * invitedUsers;
- (SInt64)invitedUsersAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppRequestCreatePrivateEventBuilder*) builder;
+ (AppRequestCreatePrivateEventBuilder*) builder;
+ (AppRequestCreatePrivateEventBuilder*) builderWithPrototype:(AppRequestCreatePrivateEvent*) prototype;
- (AppRequestCreatePrivateEventBuilder*) toBuilder;

+ (AppRequestCreatePrivateEvent*) parseFromData:(NSData*) data;
+ (AppRequestCreatePrivateEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestCreatePrivateEvent*) parseFromInputStream:(NSInputStream*) input;
+ (AppRequestCreatePrivateEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestCreatePrivateEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppRequestCreatePrivateEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppRequestCreatePrivateEventBuilder : PBGeneratedMessageBuilder {
@private
  AppRequestCreatePrivateEvent* resultCreatePrivateEvent;
}

- (AppRequestCreatePrivateEvent*) defaultInstance;

- (AppRequestCreatePrivateEventBuilder*) clear;
- (AppRequestCreatePrivateEventBuilder*) clone;

- (AppRequestCreatePrivateEvent*) build;
- (AppRequestCreatePrivateEvent*) buildPartial;

- (AppRequestCreatePrivateEventBuilder*) mergeFrom:(AppRequestCreatePrivateEvent*) other;
- (AppRequestCreatePrivateEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppRequestCreatePrivateEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTitle;
- (NSString*) title;
- (AppRequestCreatePrivateEventBuilder*) setTitle:(NSString*) value;
- (AppRequestCreatePrivateEventBuilder*) clearTitle;

- (BOOL) hasLocation;
- (NSString*) location;
- (AppRequestCreatePrivateEventBuilder*) setLocation:(NSString*) value;
- (AppRequestCreatePrivateEventBuilder*) clearLocation;

- (BOOL) hasStartTime;
- (SInt64) startTime;
- (AppRequestCreatePrivateEventBuilder*) setStartTime:(SInt64) value;
- (AppRequestCreatePrivateEventBuilder*) clearStartTime;

- (BOOL) hasEventUuid1;
- (NSData*) eventUuid1;
- (AppRequestCreatePrivateEventBuilder*) setEventUuid1:(NSData*) value;
- (AppRequestCreatePrivateEventBuilder*) clearEventUuid1;

- (BOOL) hasDescription;
- (NSString*) pb_description;
- (AppRequestCreatePrivateEventBuilder*) setDescription:(NSString*) value;
- (AppRequestCreatePrivateEventBuilder*) clearDescription;

- (PBAppendableArray *)invitedUsers;
- (SInt64)invitedUsersAtIndex:(NSUInteger)index;
- (AppRequestCreatePrivateEventBuilder *)addInvitedUsers:(SInt64)value;
- (AppRequestCreatePrivateEventBuilder *)setInvitedUsersArray:(NSArray *)array;
- (AppRequestCreatePrivateEventBuilder *)setInvitedUsersValues:(const SInt64 *)values count:(NSUInteger)count;
- (AppRequestCreatePrivateEventBuilder *)clearInvitedUsers;
@end

#define CreatePublicEvent_title @"title"
#define CreatePublicEvent_location @"location"
#define CreatePublicEvent_start_time @"startTime"
#define CreatePublicEvent_end_time @"endTime"
#define CreatePublicEvent_event_uuid1 @"eventUuid1"
#define CreatePublicEvent_description @"pb_description"
@interface AppRequestCreatePublicEvent : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStartTime_:1;
  BOOL hasEndTime_:1;
  BOOL hasTitle_:1;
  BOOL hasLocation_:1;
  BOOL hasDescription_:1;
  BOOL hasEventUuid1_:1;
  SInt64 startTime;
  SInt64 endTime;
  NSString* title;
  NSString* location;
  NSString* pb_description;
  NSData* eventUuid1;
}
- (BOOL) hasTitle;
- (BOOL) hasLocation;
- (BOOL) hasStartTime;
- (BOOL) hasEndTime;
- (BOOL) hasEventUuid1;
- (BOOL) hasDescription;
@property (readonly, strong) NSString* title;
@property (readonly, strong) NSString* location;
@property (readonly) SInt64 startTime;
@property (readonly) SInt64 endTime;
@property (readonly, strong) NSData* eventUuid1;
@property (readonly, strong) NSString* pb_description;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppRequestCreatePublicEventBuilder*) builder;
+ (AppRequestCreatePublicEventBuilder*) builder;
+ (AppRequestCreatePublicEventBuilder*) builderWithPrototype:(AppRequestCreatePublicEvent*) prototype;
- (AppRequestCreatePublicEventBuilder*) toBuilder;

+ (AppRequestCreatePublicEvent*) parseFromData:(NSData*) data;
+ (AppRequestCreatePublicEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestCreatePublicEvent*) parseFromInputStream:(NSInputStream*) input;
+ (AppRequestCreatePublicEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestCreatePublicEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppRequestCreatePublicEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppRequestCreatePublicEventBuilder : PBGeneratedMessageBuilder {
@private
  AppRequestCreatePublicEvent* resultCreatePublicEvent;
}

- (AppRequestCreatePublicEvent*) defaultInstance;

- (AppRequestCreatePublicEventBuilder*) clear;
- (AppRequestCreatePublicEventBuilder*) clone;

- (AppRequestCreatePublicEvent*) build;
- (AppRequestCreatePublicEvent*) buildPartial;

- (AppRequestCreatePublicEventBuilder*) mergeFrom:(AppRequestCreatePublicEvent*) other;
- (AppRequestCreatePublicEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppRequestCreatePublicEventBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTitle;
- (NSString*) title;
- (AppRequestCreatePublicEventBuilder*) setTitle:(NSString*) value;
- (AppRequestCreatePublicEventBuilder*) clearTitle;

- (BOOL) hasLocation;
- (NSString*) location;
- (AppRequestCreatePublicEventBuilder*) setLocation:(NSString*) value;
- (AppRequestCreatePublicEventBuilder*) clearLocation;

- (BOOL) hasStartTime;
- (SInt64) startTime;
- (AppRequestCreatePublicEventBuilder*) setStartTime:(SInt64) value;
- (AppRequestCreatePublicEventBuilder*) clearStartTime;

- (BOOL) hasEndTime;
- (SInt64) endTime;
- (AppRequestCreatePublicEventBuilder*) setEndTime:(SInt64) value;
- (AppRequestCreatePublicEventBuilder*) clearEndTime;

- (BOOL) hasEventUuid1;
- (NSData*) eventUuid1;
- (AppRequestCreatePublicEventBuilder*) setEventUuid1:(NSData*) value;
- (AppRequestCreatePublicEventBuilder*) clearEventUuid1;

- (BOOL) hasDescription;
- (NSString*) pb_description;
- (AppRequestCreatePublicEventBuilder*) setDescription:(NSString*) value;
- (AppRequestCreatePublicEventBuilder*) clearDescription;
@end

#define EventAccept_event_uuid1 @"eventUuid1"
@interface AppRequestEventAccept : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasEventUuid1_:1;
  NSData* eventUuid1;
}
- (BOOL) hasEventUuid1;
@property (readonly, strong) NSData* eventUuid1;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppRequestEventAcceptBuilder*) builder;
+ (AppRequestEventAcceptBuilder*) builder;
+ (AppRequestEventAcceptBuilder*) builderWithPrototype:(AppRequestEventAccept*) prototype;
- (AppRequestEventAcceptBuilder*) toBuilder;

+ (AppRequestEventAccept*) parseFromData:(NSData*) data;
+ (AppRequestEventAccept*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestEventAccept*) parseFromInputStream:(NSInputStream*) input;
+ (AppRequestEventAccept*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestEventAccept*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppRequestEventAccept*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppRequestEventAcceptBuilder : PBGeneratedMessageBuilder {
@private
  AppRequestEventAccept* resultEventAccept;
}

- (AppRequestEventAccept*) defaultInstance;

- (AppRequestEventAcceptBuilder*) clear;
- (AppRequestEventAcceptBuilder*) clone;

- (AppRequestEventAccept*) build;
- (AppRequestEventAccept*) buildPartial;

- (AppRequestEventAcceptBuilder*) mergeFrom:(AppRequestEventAccept*) other;
- (AppRequestEventAcceptBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppRequestEventAcceptBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEventUuid1;
- (NSData*) eventUuid1;
- (AppRequestEventAcceptBuilder*) setEventUuid1:(NSData*) value;
- (AppRequestEventAcceptBuilder*) clearEventUuid1;
@end

#define PollingParameters_offset @"offset"
#define PollingParameters_amount @"amount"
@interface AppRequestPollingParameters : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOffset_:1;
  BOOL hasAmount_:1;
  SInt64 offset;
  SInt64 amount;
}
- (BOOL) hasOffset;
- (BOOL) hasAmount;
@property (readonly) SInt64 offset;
@property (readonly) SInt64 amount;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppRequestPollingParametersBuilder*) builder;
+ (AppRequestPollingParametersBuilder*) builder;
+ (AppRequestPollingParametersBuilder*) builderWithPrototype:(AppRequestPollingParameters*) prototype;
- (AppRequestPollingParametersBuilder*) toBuilder;

+ (AppRequestPollingParameters*) parseFromData:(NSData*) data;
+ (AppRequestPollingParameters*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestPollingParameters*) parseFromInputStream:(NSInputStream*) input;
+ (AppRequestPollingParameters*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestPollingParameters*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppRequestPollingParameters*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppRequestPollingParametersBuilder : PBGeneratedMessageBuilder {
@private
  AppRequestPollingParameters* resultPollingParameters;
}

- (AppRequestPollingParameters*) defaultInstance;

- (AppRequestPollingParametersBuilder*) clear;
- (AppRequestPollingParametersBuilder*) clone;

- (AppRequestPollingParameters*) build;
- (AppRequestPollingParameters*) buildPartial;

- (AppRequestPollingParametersBuilder*) mergeFrom:(AppRequestPollingParameters*) other;
- (AppRequestPollingParametersBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppRequestPollingParametersBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOffset;
- (SInt64) offset;
- (AppRequestPollingParametersBuilder*) setOffset:(SInt64) value;
- (AppRequestPollingParametersBuilder*) clearOffset;

- (BOOL) hasAmount;
- (SInt64) amount;
- (AppRequestPollingParametersBuilder*) setAmount:(SInt64) value;
- (AppRequestPollingParametersBuilder*) clearAmount;
@end

#define FriendRequest_destination_user @"destinationUser"
#define FriendRequest_message @"message"
@interface AppRequestFriendRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDestinationUser_:1;
  BOOL hasMessage_:1;
  SInt64 destinationUser;
  NSString* message;
}
- (BOOL) hasDestinationUser;
- (BOOL) hasMessage;
@property (readonly) SInt64 destinationUser;
@property (readonly, strong) NSString* message;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppRequestFriendRequestBuilder*) builder;
+ (AppRequestFriendRequestBuilder*) builder;
+ (AppRequestFriendRequestBuilder*) builderWithPrototype:(AppRequestFriendRequest*) prototype;
- (AppRequestFriendRequestBuilder*) toBuilder;

+ (AppRequestFriendRequest*) parseFromData:(NSData*) data;
+ (AppRequestFriendRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestFriendRequest*) parseFromInputStream:(NSInputStream*) input;
+ (AppRequestFriendRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestFriendRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppRequestFriendRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppRequestFriendRequestBuilder : PBGeneratedMessageBuilder {
@private
  AppRequestFriendRequest* resultFriendRequest;
}

- (AppRequestFriendRequest*) defaultInstance;

- (AppRequestFriendRequestBuilder*) clear;
- (AppRequestFriendRequestBuilder*) clone;

- (AppRequestFriendRequest*) build;
- (AppRequestFriendRequest*) buildPartial;

- (AppRequestFriendRequestBuilder*) mergeFrom:(AppRequestFriendRequest*) other;
- (AppRequestFriendRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppRequestFriendRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDestinationUser;
- (SInt64) destinationUser;
- (AppRequestFriendRequestBuilder*) setDestinationUser:(SInt64) value;
- (AppRequestFriendRequestBuilder*) clearDestinationUser;

- (BOOL) hasMessage;
- (NSString*) message;
- (AppRequestFriendRequestBuilder*) setMessage:(NSString*) value;
- (AppRequestFriendRequestBuilder*) clearMessage;
@end

#define AcceptFriendRequest_requesting_user_id @"requestingUserId"
@interface AppRequestAcceptFriendRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRequestingUserId_:1;
  SInt64 requestingUserId;
}
- (BOOL) hasRequestingUserId;
@property (readonly) SInt64 requestingUserId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppRequestAcceptFriendRequestBuilder*) builder;
+ (AppRequestAcceptFriendRequestBuilder*) builder;
+ (AppRequestAcceptFriendRequestBuilder*) builderWithPrototype:(AppRequestAcceptFriendRequest*) prototype;
- (AppRequestAcceptFriendRequestBuilder*) toBuilder;

+ (AppRequestAcceptFriendRequest*) parseFromData:(NSData*) data;
+ (AppRequestAcceptFriendRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestAcceptFriendRequest*) parseFromInputStream:(NSInputStream*) input;
+ (AppRequestAcceptFriendRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestAcceptFriendRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppRequestAcceptFriendRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppRequestAcceptFriendRequestBuilder : PBGeneratedMessageBuilder {
@private
  AppRequestAcceptFriendRequest* resultAcceptFriendRequest;
}

- (AppRequestAcceptFriendRequest*) defaultInstance;

- (AppRequestAcceptFriendRequestBuilder*) clear;
- (AppRequestAcceptFriendRequestBuilder*) clone;

- (AppRequestAcceptFriendRequest*) build;
- (AppRequestAcceptFriendRequest*) buildPartial;

- (AppRequestAcceptFriendRequestBuilder*) mergeFrom:(AppRequestAcceptFriendRequest*) other;
- (AppRequestAcceptFriendRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppRequestAcceptFriendRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRequestingUserId;
- (SInt64) requestingUserId;
- (AppRequestAcceptFriendRequestBuilder*) setRequestingUserId:(SInt64) value;
- (AppRequestAcceptFriendRequestBuilder*) clearRequestingUserId;
@end

#define AlbumPhoto_photo @"photo"
#define AlbumPhoto_description @"pb_description"
@interface AppRequestAlbumPhoto : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDescription_:1;
  BOOL hasPhoto_:1;
  NSString* pb_description;
  NSData* photo;
}
- (BOOL) hasPhoto;
- (BOOL) hasDescription;
@property (readonly, strong) NSData* photo;
@property (readonly, strong) NSString* pb_description;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppRequestAlbumPhotoBuilder*) builder;
+ (AppRequestAlbumPhotoBuilder*) builder;
+ (AppRequestAlbumPhotoBuilder*) builderWithPrototype:(AppRequestAlbumPhoto*) prototype;
- (AppRequestAlbumPhotoBuilder*) toBuilder;

+ (AppRequestAlbumPhoto*) parseFromData:(NSData*) data;
+ (AppRequestAlbumPhoto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestAlbumPhoto*) parseFromInputStream:(NSInputStream*) input;
+ (AppRequestAlbumPhoto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestAlbumPhoto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppRequestAlbumPhoto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppRequestAlbumPhotoBuilder : PBGeneratedMessageBuilder {
@private
  AppRequestAlbumPhoto* resultAlbumPhoto;
}

- (AppRequestAlbumPhoto*) defaultInstance;

- (AppRequestAlbumPhotoBuilder*) clear;
- (AppRequestAlbumPhotoBuilder*) clone;

- (AppRequestAlbumPhoto*) build;
- (AppRequestAlbumPhoto*) buildPartial;

- (AppRequestAlbumPhotoBuilder*) mergeFrom:(AppRequestAlbumPhoto*) other;
- (AppRequestAlbumPhotoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppRequestAlbumPhotoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhoto;
- (NSData*) photo;
- (AppRequestAlbumPhotoBuilder*) setPhoto:(NSData*) value;
- (AppRequestAlbumPhotoBuilder*) clearPhoto;

- (BOOL) hasDescription;
- (NSString*) pb_description;
- (AppRequestAlbumPhotoBuilder*) setDescription:(NSString*) value;
- (AppRequestAlbumPhotoBuilder*) clearDescription;
@end

#define PhotoAlbum_photos @"photos"
#define PhotoAlbum_AlbumDescription @"albumDescription"
@interface AppRequestPhotoAlbum : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAlbumDescription_:1;
  NSString* albumDescription;
  NSMutableArray * photosArray;
}
- (BOOL) hasAlbumDescription;
@property (readonly, strong) NSArray * photos;
@property (readonly, strong) NSString* albumDescription;
- (AppRequestAlbumPhoto*)photosAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppRequestPhotoAlbumBuilder*) builder;
+ (AppRequestPhotoAlbumBuilder*) builder;
+ (AppRequestPhotoAlbumBuilder*) builderWithPrototype:(AppRequestPhotoAlbum*) prototype;
- (AppRequestPhotoAlbumBuilder*) toBuilder;

+ (AppRequestPhotoAlbum*) parseFromData:(NSData*) data;
+ (AppRequestPhotoAlbum*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestPhotoAlbum*) parseFromInputStream:(NSInputStream*) input;
+ (AppRequestPhotoAlbum*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestPhotoAlbum*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppRequestPhotoAlbum*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppRequestPhotoAlbumBuilder : PBGeneratedMessageBuilder {
@private
  AppRequestPhotoAlbum* resultPhotoAlbum;
}

- (AppRequestPhotoAlbum*) defaultInstance;

- (AppRequestPhotoAlbumBuilder*) clear;
- (AppRequestPhotoAlbumBuilder*) clone;

- (AppRequestPhotoAlbum*) build;
- (AppRequestPhotoAlbum*) buildPartial;

- (AppRequestPhotoAlbumBuilder*) mergeFrom:(AppRequestPhotoAlbum*) other;
- (AppRequestPhotoAlbumBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppRequestPhotoAlbumBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)photos;
- (AppRequestAlbumPhoto*)photosAtIndex:(NSUInteger)index;
- (AppRequestPhotoAlbumBuilder *)addPhotos:(AppRequestAlbumPhoto*)value;
- (AppRequestPhotoAlbumBuilder *)setPhotosArray:(NSArray *)array;
- (AppRequestPhotoAlbumBuilder *)clearPhotos;

- (BOOL) hasAlbumDescription;
- (NSString*) albumDescription;
- (AppRequestPhotoAlbumBuilder*) setAlbumDescription:(NSString*) value;
- (AppRequestPhotoAlbumBuilder*) clearAlbumDescription;
@end

#define UpdateProfile_email @"email"
#define UpdateProfile_description @"pb_description"
#define UpdateProfile_location @"location"
#define UpdateProfile_nickname @"nickname"
#define UpdateProfile_password @"password"
#define UpdateProfile_profile_photo @"profilePhoto"
#define UpdateProfile_personal_albums @"personalAlbums"
@interface AppRequestUpdateProfile : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasEmail_:1;
  BOOL hasDescription_:1;
  BOOL hasLocation_:1;
  BOOL hasNickname_:1;
  BOOL hasPassword_:1;
  BOOL hasProfilePhoto_:1;
  NSString* email;
  NSString* pb_description;
  NSString* location;
  NSString* nickname;
  NSString* password;
  NSData* profilePhoto;
  NSMutableArray * personalAlbumsArray;
}
- (BOOL) hasEmail;
- (BOOL) hasDescription;
- (BOOL) hasLocation;
- (BOOL) hasNickname;
- (BOOL) hasPassword;
- (BOOL) hasProfilePhoto;
@property (readonly, strong) NSString* email;
@property (readonly, strong) NSString* pb_description;
@property (readonly, strong) NSString* location;
@property (readonly, strong) NSString* nickname;
@property (readonly, strong) NSString* password;
@property (readonly, strong) NSData* profilePhoto;
@property (readonly, strong) NSArray * personalAlbums;
- (AppRequestPhotoAlbum*)personalAlbumsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppRequestUpdateProfileBuilder*) builder;
+ (AppRequestUpdateProfileBuilder*) builder;
+ (AppRequestUpdateProfileBuilder*) builderWithPrototype:(AppRequestUpdateProfile*) prototype;
- (AppRequestUpdateProfileBuilder*) toBuilder;

+ (AppRequestUpdateProfile*) parseFromData:(NSData*) data;
+ (AppRequestUpdateProfile*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestUpdateProfile*) parseFromInputStream:(NSInputStream*) input;
+ (AppRequestUpdateProfile*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppRequestUpdateProfile*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppRequestUpdateProfile*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppRequestUpdateProfileBuilder : PBGeneratedMessageBuilder {
@private
  AppRequestUpdateProfile* resultUpdateProfile;
}

- (AppRequestUpdateProfile*) defaultInstance;

- (AppRequestUpdateProfileBuilder*) clear;
- (AppRequestUpdateProfileBuilder*) clone;

- (AppRequestUpdateProfile*) build;
- (AppRequestUpdateProfile*) buildPartial;

- (AppRequestUpdateProfileBuilder*) mergeFrom:(AppRequestUpdateProfile*) other;
- (AppRequestUpdateProfileBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppRequestUpdateProfileBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEmail;
- (NSString*) email;
- (AppRequestUpdateProfileBuilder*) setEmail:(NSString*) value;
- (AppRequestUpdateProfileBuilder*) clearEmail;

- (BOOL) hasDescription;
- (NSString*) pb_description;
- (AppRequestUpdateProfileBuilder*) setDescription:(NSString*) value;
- (AppRequestUpdateProfileBuilder*) clearDescription;

- (BOOL) hasLocation;
- (NSString*) location;
- (AppRequestUpdateProfileBuilder*) setLocation:(NSString*) value;
- (AppRequestUpdateProfileBuilder*) clearLocation;

- (BOOL) hasNickname;
- (NSString*) nickname;
- (AppRequestUpdateProfileBuilder*) setNickname:(NSString*) value;
- (AppRequestUpdateProfileBuilder*) clearNickname;

- (BOOL) hasPassword;
- (NSString*) password;
- (AppRequestUpdateProfileBuilder*) setPassword:(NSString*) value;
- (AppRequestUpdateProfileBuilder*) clearPassword;

- (BOOL) hasProfilePhoto;
- (NSData*) profilePhoto;
- (AppRequestUpdateProfileBuilder*) setProfilePhoto:(NSData*) value;
- (AppRequestUpdateProfileBuilder*) clearProfilePhoto;

- (NSMutableArray *)personalAlbums;
- (AppRequestPhotoAlbum*)personalAlbumsAtIndex:(NSUInteger)index;
- (AppRequestUpdateProfileBuilder *)addPersonalAlbums:(AppRequestPhotoAlbum*)value;
- (AppRequestUpdateProfileBuilder *)setPersonalAlbumsArray:(NSArray *)array;
- (AppRequestUpdateProfileBuilder *)clearPersonalAlbums;
@end

@interface AppRequestBuilder : PBGeneratedMessageBuilder {
@private
  AppRequest* resultAppRequest;
}

- (AppRequest*) defaultInstance;

- (AppRequestBuilder*) clear;
- (AppRequestBuilder*) clone;

- (AppRequest*) build;
- (AppRequest*) buildPartial;

- (AppRequestBuilder*) mergeFrom:(AppRequest*) other;
- (AppRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhoneId;
- (SInt64) phoneId;
- (AppRequestBuilder*) setPhoneId:(SInt64) value;
- (AppRequestBuilder*) clearPhoneId;

- (BOOL) hasMsgType;
- (AppRequestMessageType) msgType;
- (AppRequestBuilder*) setMsgType:(AppRequestMessageType) value;
- (AppRequestBuilder*) clearMsgType;

- (BOOL) hasRegMsg;
- (AppRequestRegisterMessage*) regMsg;
- (AppRequestBuilder*) setRegMsg:(AppRequestRegisterMessage*) value;
- (AppRequestBuilder*) setRegMsgBuilder:(AppRequestRegisterMessageBuilder*) builderForValue;
- (AppRequestBuilder*) mergeRegMsg:(AppRequestRegisterMessage*) value;
- (AppRequestBuilder*) clearRegMsg;

- (BOOL) hasLoginMsg;
- (AppRequestLoginMessage*) loginMsg;
- (AppRequestBuilder*) setLoginMsg:(AppRequestLoginMessage*) value;
- (AppRequestBuilder*) setLoginMsgBuilder:(AppRequestLoginMessageBuilder*) builderForValue;
- (AppRequestBuilder*) mergeLoginMsg:(AppRequestLoginMessage*) value;
- (AppRequestBuilder*) clearLoginMsg;

- (BOOL) hasCreatePrivateEvent;
- (AppRequestCreatePrivateEvent*) createPrivateEvent;
- (AppRequestBuilder*) setCreatePrivateEvent:(AppRequestCreatePrivateEvent*) value;
- (AppRequestBuilder*) setCreatePrivateEventBuilder:(AppRequestCreatePrivateEventBuilder*) builderForValue;
- (AppRequestBuilder*) mergeCreatePrivateEvent:(AppRequestCreatePrivateEvent*) value;
- (AppRequestBuilder*) clearCreatePrivateEvent;

- (BOOL) hasCreatePublicEvent;
- (AppRequestCreatePublicEvent*) createPublicEvent;
- (AppRequestBuilder*) setCreatePublicEvent:(AppRequestCreatePublicEvent*) value;
- (AppRequestBuilder*) setCreatePublicEventBuilder:(AppRequestCreatePublicEventBuilder*) builderForValue;
- (AppRequestBuilder*) mergeCreatePublicEvent:(AppRequestCreatePublicEvent*) value;
- (AppRequestBuilder*) clearCreatePublicEvent;

- (BOOL) hasAcceptEvent;
- (AppRequestEventAccept*) acceptEvent;
- (AppRequestBuilder*) setAcceptEvent:(AppRequestEventAccept*) value;
- (AppRequestBuilder*) setAcceptEventBuilder:(AppRequestEventAcceptBuilder*) builderForValue;
- (AppRequestBuilder*) mergeAcceptEvent:(AppRequestEventAccept*) value;
- (AppRequestBuilder*) clearAcceptEvent;

- (BOOL) hasPollParams;
- (AppRequestPollingParameters*) pollParams;
- (AppRequestBuilder*) setPollParams:(AppRequestPollingParameters*) value;
- (AppRequestBuilder*) setPollParamsBuilder:(AppRequestPollingParametersBuilder*) builderForValue;
- (AppRequestBuilder*) mergePollParams:(AppRequestPollingParameters*) value;
- (AppRequestBuilder*) clearPollParams;

- (BOOL) hasFriendRequest;
- (AppRequestFriendRequest*) friendRequest;
- (AppRequestBuilder*) setFriendRequest:(AppRequestFriendRequest*) value;
- (AppRequestBuilder*) setFriendRequestBuilder:(AppRequestFriendRequestBuilder*) builderForValue;
- (AppRequestBuilder*) mergeFriendRequest:(AppRequestFriendRequest*) value;
- (AppRequestBuilder*) clearFriendRequest;

- (BOOL) hasAcceptFriendRequest;
- (AppRequestAcceptFriendRequest*) acceptFriendRequest;
- (AppRequestBuilder*) setAcceptFriendRequest:(AppRequestAcceptFriendRequest*) value;
- (AppRequestBuilder*) setAcceptFriendRequestBuilder:(AppRequestAcceptFriendRequestBuilder*) builderForValue;
- (AppRequestBuilder*) mergeAcceptFriendRequest:(AppRequestAcceptFriendRequest*) value;
- (AppRequestBuilder*) clearAcceptFriendRequest;

- (BOOL) hasUpdateProfile;
- (AppRequestUpdateProfile*) updateProfile;
- (AppRequestBuilder*) setUpdateProfile:(AppRequestUpdateProfile*) value;
- (AppRequestBuilder*) setUpdateProfileBuilder:(AppRequestUpdateProfileBuilder*) builderForValue;
- (AppRequestBuilder*) mergeUpdateProfile:(AppRequestUpdateProfile*) value;
- (AppRequestBuilder*) clearUpdateProfile;

- (PBAppendableArray *)requestUserInfo;
- (SInt64)requestUserInfoAtIndex:(NSUInteger)index;
- (AppRequestBuilder *)addRequestUserInfo:(SInt64)value;
- (AppRequestBuilder *)setRequestUserInfoArray:(NSArray *)array;
- (AppRequestBuilder *)setRequestUserInfoValues:(const SInt64 *)values count:(NSUInteger)count;
- (AppRequestBuilder *)clearRequestUserInfo;
@end

#define AppReply_response_type @"responseType"
#define AppReply_event_uuid @"eventUuid"
#define AppReply_users @"users"
#define AppReply_friend_requests @"friendRequests"
#define AppReply_event_info @"eventInfo"
#define AppReply_accepted_friends @"acceptedFriends"
@interface AppReply : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasEventUuid_:1;
  BOOL hasResponseType_:1;
  AppReplyEventUUID* eventUuid;
  AppReplyResponseType responseType;
  PBAppendableArray * acceptedFriendsArray;
  NSMutableArray * usersArray;
  NSMutableArray * friendRequestsArray;
  NSMutableArray * eventInfoArray;
}
- (BOOL) hasResponseType;
- (BOOL) hasEventUuid;
@property (readonly) AppReplyResponseType responseType;
@property (readonly, strong) AppReplyEventUUID* eventUuid;
@property (readonly, strong) NSArray * users;
@property (readonly, strong) NSArray * friendRequests;
@property (readonly, strong) NSArray * eventInfo;
@property (readonly, strong) PBArray * acceptedFriends;
- (AppReplyUser*)usersAtIndex:(NSUInteger)index;
- (AppReplyFriendRequest*)friendRequestsAtIndex:(NSUInteger)index;
- (AppReplyEventInfo*)eventInfoAtIndex:(NSUInteger)index;
- (SInt64)acceptedFriendsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppReplyBuilder*) builder;
+ (AppReplyBuilder*) builder;
+ (AppReplyBuilder*) builderWithPrototype:(AppReply*) prototype;
- (AppReplyBuilder*) toBuilder;

+ (AppReply*) parseFromData:(NSData*) data;
+ (AppReply*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppReply*) parseFromInputStream:(NSInputStream*) input;
+ (AppReply*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppReply*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppReply*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define EventUUID_event_uuid1 @"eventUuid1"
@interface AppReplyEventUUID : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasEventUuid1_:1;
  NSData* eventUuid1;
}
- (BOOL) hasEventUuid1;
@property (readonly, strong) NSData* eventUuid1;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppReplyEventUUIDBuilder*) builder;
+ (AppReplyEventUUIDBuilder*) builder;
+ (AppReplyEventUUIDBuilder*) builderWithPrototype:(AppReplyEventUUID*) prototype;
- (AppReplyEventUUIDBuilder*) toBuilder;

+ (AppReplyEventUUID*) parseFromData:(NSData*) data;
+ (AppReplyEventUUID*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppReplyEventUUID*) parseFromInputStream:(NSInputStream*) input;
+ (AppReplyEventUUID*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppReplyEventUUID*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppReplyEventUUID*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppReplyEventUUIDBuilder : PBGeneratedMessageBuilder {
@private
  AppReplyEventUUID* resultEventUuid;
}

- (AppReplyEventUUID*) defaultInstance;

- (AppReplyEventUUIDBuilder*) clear;
- (AppReplyEventUUIDBuilder*) clone;

- (AppReplyEventUUID*) build;
- (AppReplyEventUUID*) buildPartial;

- (AppReplyEventUUIDBuilder*) mergeFrom:(AppReplyEventUUID*) other;
- (AppReplyEventUUIDBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppReplyEventUUIDBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEventUuid1;
- (NSData*) eventUuid1;
- (AppReplyEventUUIDBuilder*) setEventUuid1:(NSData*) value;
- (AppReplyEventUUIDBuilder*) clearEventUuid1;
@end

#define User_phone_number @"phoneNumber"
#define User_nickname @"nickname"
#define User_is_male @"isMale"
#define User_profile_photo @"profilePhoto"
#define User_email @"email"
#define User_description @"pb_description"
#define User_location @"location"
@interface AppReplyUser : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIsMale_:1;
  BOOL hasPhoneNumber_:1;
  BOOL hasNickname_:1;
  BOOL hasEmail_:1;
  BOOL hasDescription_:1;
  BOOL hasLocation_:1;
  BOOL hasProfilePhoto_:1;
  BOOL isMale_:1;
  SInt64 phoneNumber;
  NSString* nickname;
  NSString* email;
  NSString* pb_description;
  NSString* location;
  NSData* profilePhoto;
}
- (BOOL) hasPhoneNumber;
- (BOOL) hasNickname;
- (BOOL) hasIsMale;
- (BOOL) hasProfilePhoto;
- (BOOL) hasEmail;
- (BOOL) hasDescription;
- (BOOL) hasLocation;
@property (readonly) SInt64 phoneNumber;
@property (readonly, strong) NSString* nickname;
- (BOOL) isMale;
@property (readonly, strong) NSData* profilePhoto;
@property (readonly, strong) NSString* email;
@property (readonly, strong) NSString* pb_description;
@property (readonly, strong) NSString* location;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppReplyUserBuilder*) builder;
+ (AppReplyUserBuilder*) builder;
+ (AppReplyUserBuilder*) builderWithPrototype:(AppReplyUser*) prototype;
- (AppReplyUserBuilder*) toBuilder;

+ (AppReplyUser*) parseFromData:(NSData*) data;
+ (AppReplyUser*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppReplyUser*) parseFromInputStream:(NSInputStream*) input;
+ (AppReplyUser*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppReplyUser*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppReplyUser*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppReplyUserBuilder : PBGeneratedMessageBuilder {
@private
  AppReplyUser* resultUser;
}

- (AppReplyUser*) defaultInstance;

- (AppReplyUserBuilder*) clear;
- (AppReplyUserBuilder*) clone;

- (AppReplyUser*) build;
- (AppReplyUser*) buildPartial;

- (AppReplyUserBuilder*) mergeFrom:(AppReplyUser*) other;
- (AppReplyUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppReplyUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPhoneNumber;
- (SInt64) phoneNumber;
- (AppReplyUserBuilder*) setPhoneNumber:(SInt64) value;
- (AppReplyUserBuilder*) clearPhoneNumber;

- (BOOL) hasNickname;
- (NSString*) nickname;
- (AppReplyUserBuilder*) setNickname:(NSString*) value;
- (AppReplyUserBuilder*) clearNickname;

- (BOOL) hasIsMale;
- (BOOL) isMale;
- (AppReplyUserBuilder*) setIsMale:(BOOL) value;
- (AppReplyUserBuilder*) clearIsMale;

- (BOOL) hasProfilePhoto;
- (NSData*) profilePhoto;
- (AppReplyUserBuilder*) setProfilePhoto:(NSData*) value;
- (AppReplyUserBuilder*) clearProfilePhoto;

- (BOOL) hasEmail;
- (NSString*) email;
- (AppReplyUserBuilder*) setEmail:(NSString*) value;
- (AppReplyUserBuilder*) clearEmail;

- (BOOL) hasDescription;
- (NSString*) pb_description;
- (AppReplyUserBuilder*) setDescription:(NSString*) value;
- (AppReplyUserBuilder*) clearDescription;

- (BOOL) hasLocation;
- (NSString*) location;
- (AppReplyUserBuilder*) setLocation:(NSString*) value;
- (AppReplyUserBuilder*) clearLocation;
@end

#define FriendRequest_request_origin_user_id @"requestOriginUserId"
#define FriendRequest_request_message @"requestMessage"
@interface AppReplyFriendRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRequestOriginUserId_:1;
  BOOL hasRequestMessage_:1;
  SInt64 requestOriginUserId;
  NSString* requestMessage;
}
- (BOOL) hasRequestOriginUserId;
- (BOOL) hasRequestMessage;
@property (readonly) SInt64 requestOriginUserId;
@property (readonly, strong) NSString* requestMessage;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppReplyFriendRequestBuilder*) builder;
+ (AppReplyFriendRequestBuilder*) builder;
+ (AppReplyFriendRequestBuilder*) builderWithPrototype:(AppReplyFriendRequest*) prototype;
- (AppReplyFriendRequestBuilder*) toBuilder;

+ (AppReplyFriendRequest*) parseFromData:(NSData*) data;
+ (AppReplyFriendRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppReplyFriendRequest*) parseFromInputStream:(NSInputStream*) input;
+ (AppReplyFriendRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppReplyFriendRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppReplyFriendRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppReplyFriendRequestBuilder : PBGeneratedMessageBuilder {
@private
  AppReplyFriendRequest* resultFriendRequest;
}

- (AppReplyFriendRequest*) defaultInstance;

- (AppReplyFriendRequestBuilder*) clear;
- (AppReplyFriendRequestBuilder*) clone;

- (AppReplyFriendRequest*) build;
- (AppReplyFriendRequest*) buildPartial;

- (AppReplyFriendRequestBuilder*) mergeFrom:(AppReplyFriendRequest*) other;
- (AppReplyFriendRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppReplyFriendRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRequestOriginUserId;
- (SInt64) requestOriginUserId;
- (AppReplyFriendRequestBuilder*) setRequestOriginUserId:(SInt64) value;
- (AppReplyFriendRequestBuilder*) clearRequestOriginUserId;

- (BOOL) hasRequestMessage;
- (NSString*) requestMessage;
- (AppReplyFriendRequestBuilder*) setRequestMessage:(NSString*) value;
- (AppReplyFriendRequestBuilder*) clearRequestMessage;
@end

#define EventInfo_title @"title"
#define EventInfo_location @"location"
#define EventInfo_time @"time"
#define EventInfo_event_uuid @"eventUuid"
#define EventInfo_is_public @"isPublic"
#define EventInfo_description @"pb_description"
#define EventInfo_accepted_users @"acceptedUsers"
@interface AppReplyEventInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIsPublic_:1;
  BOOL hasTime_:1;
  BOOL hasTitle_:1;
  BOOL hasLocation_:1;
  BOOL hasDescription_:1;
  BOOL hasEventUuid_:1;
  BOOL isPublic_:1;
  SInt64 time;
  NSString* title;
  NSString* location;
  NSString* pb_description;
  NSData* eventUuid;
  PBAppendableArray * acceptedUsersArray;
}
- (BOOL) hasTitle;
- (BOOL) hasLocation;
- (BOOL) hasTime;
- (BOOL) hasEventUuid;
- (BOOL) hasIsPublic;
- (BOOL) hasDescription;
@property (readonly, strong) NSString* title;
@property (readonly, strong) NSString* location;
@property (readonly) SInt64 time;
@property (readonly, strong) NSData* eventUuid;
- (BOOL) isPublic;
@property (readonly, strong) NSString* pb_description;
@property (readonly, strong) PBArray * acceptedUsers;
- (SInt64)acceptedUsersAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AppReplyEventInfoBuilder*) builder;
+ (AppReplyEventInfoBuilder*) builder;
+ (AppReplyEventInfoBuilder*) builderWithPrototype:(AppReplyEventInfo*) prototype;
- (AppReplyEventInfoBuilder*) toBuilder;

+ (AppReplyEventInfo*) parseFromData:(NSData*) data;
+ (AppReplyEventInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppReplyEventInfo*) parseFromInputStream:(NSInputStream*) input;
+ (AppReplyEventInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AppReplyEventInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AppReplyEventInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AppReplyEventInfoBuilder : PBGeneratedMessageBuilder {
@private
  AppReplyEventInfo* resultEventInfo;
}

- (AppReplyEventInfo*) defaultInstance;

- (AppReplyEventInfoBuilder*) clear;
- (AppReplyEventInfoBuilder*) clone;

- (AppReplyEventInfo*) build;
- (AppReplyEventInfo*) buildPartial;

- (AppReplyEventInfoBuilder*) mergeFrom:(AppReplyEventInfo*) other;
- (AppReplyEventInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppReplyEventInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTitle;
- (NSString*) title;
- (AppReplyEventInfoBuilder*) setTitle:(NSString*) value;
- (AppReplyEventInfoBuilder*) clearTitle;

- (BOOL) hasLocation;
- (NSString*) location;
- (AppReplyEventInfoBuilder*) setLocation:(NSString*) value;
- (AppReplyEventInfoBuilder*) clearLocation;

- (BOOL) hasTime;
- (SInt64) time;
- (AppReplyEventInfoBuilder*) setTime:(SInt64) value;
- (AppReplyEventInfoBuilder*) clearTime;

- (BOOL) hasEventUuid;
- (NSData*) eventUuid;
- (AppReplyEventInfoBuilder*) setEventUuid:(NSData*) value;
- (AppReplyEventInfoBuilder*) clearEventUuid;

- (BOOL) hasIsPublic;
- (BOOL) isPublic;
- (AppReplyEventInfoBuilder*) setIsPublic:(BOOL) value;
- (AppReplyEventInfoBuilder*) clearIsPublic;

- (BOOL) hasDescription;
- (NSString*) pb_description;
- (AppReplyEventInfoBuilder*) setDescription:(NSString*) value;
- (AppReplyEventInfoBuilder*) clearDescription;

- (PBAppendableArray *)acceptedUsers;
- (SInt64)acceptedUsersAtIndex:(NSUInteger)index;
- (AppReplyEventInfoBuilder *)addAcceptedUsers:(SInt64)value;
- (AppReplyEventInfoBuilder *)setAcceptedUsersArray:(NSArray *)array;
- (AppReplyEventInfoBuilder *)setAcceptedUsersValues:(const SInt64 *)values count:(NSUInteger)count;
- (AppReplyEventInfoBuilder *)clearAcceptedUsers;
@end

@interface AppReplyBuilder : PBGeneratedMessageBuilder {
@private
  AppReply* resultAppReply;
}

- (AppReply*) defaultInstance;

- (AppReplyBuilder*) clear;
- (AppReplyBuilder*) clone;

- (AppReply*) build;
- (AppReply*) buildPartial;

- (AppReplyBuilder*) mergeFrom:(AppReply*) other;
- (AppReplyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AppReplyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasResponseType;
- (AppReplyResponseType) responseType;
- (AppReplyBuilder*) setResponseType:(AppReplyResponseType) value;
- (AppReplyBuilder*) clearResponseType;

- (BOOL) hasEventUuid;
- (AppReplyEventUUID*) eventUuid;
- (AppReplyBuilder*) setEventUuid:(AppReplyEventUUID*) value;
- (AppReplyBuilder*) setEventUuidBuilder:(AppReplyEventUUIDBuilder*) builderForValue;
- (AppReplyBuilder*) mergeEventUuid:(AppReplyEventUUID*) value;
- (AppReplyBuilder*) clearEventUuid;

- (NSMutableArray *)users;
- (AppReplyUser*)usersAtIndex:(NSUInteger)index;
- (AppReplyBuilder *)addUsers:(AppReplyUser*)value;
- (AppReplyBuilder *)setUsersArray:(NSArray *)array;
- (AppReplyBuilder *)clearUsers;

- (NSMutableArray *)friendRequests;
- (AppReplyFriendRequest*)friendRequestsAtIndex:(NSUInteger)index;
- (AppReplyBuilder *)addFriendRequests:(AppReplyFriendRequest*)value;
- (AppReplyBuilder *)setFriendRequestsArray:(NSArray *)array;
- (AppReplyBuilder *)clearFriendRequests;

- (NSMutableArray *)eventInfo;
- (AppReplyEventInfo*)eventInfoAtIndex:(NSUInteger)index;
- (AppReplyBuilder *)addEventInfo:(AppReplyEventInfo*)value;
- (AppReplyBuilder *)setEventInfoArray:(NSArray *)array;
- (AppReplyBuilder *)clearEventInfo;

- (PBAppendableArray *)acceptedFriends;
- (SInt64)acceptedFriendsAtIndex:(NSUInteger)index;
- (AppReplyBuilder *)addAcceptedFriends:(SInt64)value;
- (AppReplyBuilder *)setAcceptedFriendsArray:(NSArray *)array;
- (AppReplyBuilder *)setAcceptedFriendsValues:(const SInt64 *)values count:(NSUInteger)count;
- (AppReplyBuilder *)clearAcceptedFriends;
@end


// @@protoc_insertion_point(global_scope)
